'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const zlib = require('node:zlib');
const { execFileSync } = require('node:child_process');
const checkpoint = require('../scripts/generated-data-checkpoint.cjs');
const prepare = require('../scripts/prepare-daily-prediction-git-save');
const archive = require('../scripts/daily-prediction-source-archive');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'generated-checkpoint-test-'));
const raw = 'data/predictions/20261010.json';
const gzip = 'data/predictions/source-archives/20261010.json.gz';
const meta = 'data/predictions/source-archives/20261010.meta.json';
const monitor = 'data/stats/active-100r-early-monitor.json';
let checks = 0;
const git = (cwd, args) => execFileSync('git', args, { cwd, encoding: 'utf8', stdio: 'pipe' }).trimEnd();
const write = (cwd, file, value) => { fs.mkdirSync(path.dirname(path.join(cwd, file)), { recursive: true }); fs.writeFileSync(path.join(cwd, file), value); };
function commit(cwd) { git(cwd, ['add', '.']); git(cwd, ['commit', '-m', 'fixture']); }
function fixture(name, profile = 'negative-clip', changed = true, archived = true, originalBlobCount = 0) {
  const dir = path.join(root, name), work = path.join(dir, 'work'), remote = path.join(dir, 'remote.git'), other = path.join(dir, 'other');
  fs.mkdirSync(work, { recursive: true });
  git(work, ['init', '-b', 'main']);
  git(work, ['config', 'user.name', 'fixture']); git(work, ['config', 'user.email', 'fixture@example.invalid']);
  const original = { date: '20261010', predictions: [{ raceKey: 'fixture', tickets: ['fixture-ticket'] }], verificationPredictions: [], originalEvidence: { preserve: true } };
  write(work, raw, JSON.stringify(original) + '\n'); write(work, monitor, '{"baseline":true}\n');
  write(work, 'scripts/fixture.cjs', '// immutable generator\n');
  write(work, 'data/results/20261010.json', '{"originalResult":true}\n');
  write(work, 'data/notes/fixture.md', 'original note\n');
  const originalPaths = Array.from({ length: originalBlobCount }, (_, i) => `data/originals/${i}.bin`);
  originalPaths.forEach((file, i) => write(work, file, Buffer.alloc(128 * 1024, i + 1)));
  commit(work);
  const baseSha = git(work, ['rev-parse', 'HEAD']);
  git(dir, ['clone', '--bare', work, remote]); git(work, ['remote', 'add', 'origin', 'file://' + remote]);
  git(dir, ['clone', 'file://' + remote, other]); git(other, ['config', 'user.name', 'other']); git(other, ['config', 'user.email', 'other@example.invalid']);
  const next = { ...original, frameRiseFallNegativeClipShadowAb: { fixture: true } };
  if (changed) {
    if (profile === 'negative-clip') {
      write(work, raw, JSON.stringify(next, null, 2) + '\n');
      prepare.preparePredictionGitSave({ rootDirectory: work, date: '20261010', rawSaveLimitBytes: archived ? 1 : 100000 });
    } else write(work, monitor, '{"refreshed":true}\n');
  }
  const directory = path.join(dir, 'checkpoint');
  const packed = checkpoint.pack({ root: work, profile, date: profile === 'negative-clip' ? '20261010' : '', output: directory, runId: '101', runAttempt: '1' });
  const expected = { profile, date: packed.date, baseSha, runId: '101', runAttempt: '1', artifactId: '202', manifestSha256: packed.manifestSha256 };
  return { dir, work, remote, other, directory, expected, original, next, packed, originalPaths };
}
function publish(f, beforePush) { return checkpoint.publish({ root: f.work, directory: f.directory, expected: f.expected, beforePush }); }
function advance(f, file, value) {
  git(f.other, ['fetch', 'origin', 'main']); git(f.other, ['reset', '--hard', 'origin/main']);
  write(f.other, file, value); commit(f.other); git(f.other, ['push', 'origin', 'main']);
}
function remoteFile(f, file) { return execFileSync('git', ['show', `main:${file}`], { cwd: f.remote, stdio: 'pipe' }); }
function mutateManifest(f, change) {
  const file = path.join(f.directory, 'manifest.json'), manifest = JSON.parse(fs.readFileSync(file));
  change(manifest); const bytes = Buffer.from(JSON.stringify(manifest) + '\n'); fs.writeFileSync(file, bytes); f.expected.manifestSha256 = checkpoint.sha256(bytes);
}
function test(name, fn) { fn(); checks++; console.log('ok:', name); }
try {
  test('archive + metadata are preserved exactly; standard reader restores generated bytes; original raw/results/notes unchanged', () => {
    const f = fixture('archive');
    const before = git(f.work, ['status', '--porcelain']);
    const bundleBefore = fs.readFileSync(path.join(f.directory, 'manifest.json'));
    const result = publish(f);
    assert.equal(result.status, 'saved'); assert.equal(result.attempt, 1);
    assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.original);
    assert.deepEqual(JSON.parse(zlib.gunzipSync(remoteFile(f, gzip))), f.next);
    assert.deepEqual(JSON.parse(remoteFile(f, 'data/results/20261010.json')), { originalResult: true });
    assert.equal(remoteFile(f, 'data/notes/fixture.md').toString(), 'original note\n');
    const restored = path.join(f.dir, 'restored');
    for (const file of [gzip, meta]) write(restored, file, remoteFile(f, file));
    archive.restorePredictionSource({ rootDirectory: restored, date: '20261010' });
    assert.deepEqual(JSON.parse(fs.readFileSync(path.join(restored, raw))), f.next);
    assert.equal(git(f.work, ['status', '--porcelain']), before, 'caller index/worktree untouched');
    assert.deepEqual(fs.readFileSync(path.join(f.directory, 'manifest.json')), bundleBefore);
    assert.deepEqual(git(f.remote, ['diff-tree', '--no-commit-id', '--name-only', '-r', result.savedSha]).split('\n'), [gzip, meta]);
    assert.equal(publish(f).status, 'already-persisted', 'replay of exact bytes creates no extra commit');
  });
  for (const profile of ['negative-clip', 'active-100r']) {
    test(`${profile}: true partial clone preserves 13 missing remote originals through an exact push`, () => {
      const f = fixture('promisor-' + profile, profile, true, true, 13);
      const partial = path.join(f.dir, 'partial');
      git(f.remote, ['config', 'uploadpack.allowFilter', 'true']);
      git(f.dir, ['clone', '--filter=blob:none', '--no-checkout', '--depth=1', '--branch=main', 'file://' + f.remote, partial]);
      git(partial, ['sparse-checkout', 'set', 'scripts']);
      git(partial, ['checkout', 'main']);
      assert.equal(git(partial, ['config', '--get', 'remote.origin.promisor']), 'true');
      assert.equal(git(partial, ['config', '--get', 'remote.origin.partialclonefilter']), 'blob:none');
      assert.equal(git(partial, ['rev-parse', '--is-shallow-repository']), 'true');
      // Enumerate only local objects: unlike cat-file -e, this cannot lazy-fetch.
      const localObjects = () => new Set(git(partial, ['cat-file', '--batch-all-objects', '--batch-check=%(objectname)']).split('\n'));
      const originals = f.originalPaths.map(file => git(f.remote, ['rev-parse', `main:${file}`]));
      const assertOriginalsMissing = () => {
        const present = localObjects();
        assert.equal(originals.filter(oid => !present.has(oid)).length, 13);
        assert.equal(fs.existsSync(path.join(partial, 'data')), false);
      };
      originals.forEach(oid => assert.equal(git(f.remote, ['cat-file', '-t', oid]), 'blob'));
      assertOriginalsMissing();
      const manifest = JSON.parse(fs.readFileSync(path.join(f.directory, 'manifest.json')));
      const first = manifest.files.find(file => file.operation === 'write');
      const payload = path.join(f.directory, 'files', first.sha256), bytes = fs.readFileSync(payload);
      fs.unlinkSync(payload);
      let pushes = 0;
      assert.throws(() => checkpoint.publish({ root: partial, directory: f.directory, expected: f.expected, beforePush: () => pushes++ }));
      assert.equal(pushes, 0); assert.equal(git(f.remote, ['rev-parse', 'main']), f.expected.baseSha);
      assertOriginalsMissing(); fs.writeFileSync(payload, bytes);
      const before = git(partial, ['status', '--porcelain']);
      const result = checkpoint.publish({ root: partial, directory: f.directory, expected: f.expected, beforePush: () => {
        assertOriginalsMissing();
        const present = localObjects();
        for (const file of manifest.files.filter(file => file.operation === 'write'))
          assert.ok(present.has(file.newBlob), 'every generated blob must already exist locally');
      } });
      assert.equal(result.status, 'saved'); assertOriginalsMissing();
      assert.equal(git(partial, ['status', '--porcelain']), before);
      assert.deepEqual(git(f.remote, ['diff-tree', '--no-commit-id', '--name-only', '-r', result.savedSha]).split('\n').sort(), manifest.files.map(file => file.path).sort());
      for (const file of manifest.files.filter(file => file.operation === 'write')) {
        assert.equal(git(f.remote, ['rev-parse', `main:${file.path}`]), file.newBlob);
        assert.deepEqual(remoteFile(f, file.path), fs.readFileSync(path.join(f.directory, 'files', file.sha256)));
      }
      assert.deepEqual(f.originalPaths.map(file => git(f.remote, ['rev-parse', `main:${file}`])), originals);
      assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.original);
    });
    test(`${profile}: non-conflicting push race retries exact frozen payload and preserves competing data`, () => {
      const f = fixture('retry-' + profile, profile);
      const result = publish(f, ({ attempt }) => { if (attempt === 1) advance(f, 'data/stats/other.json', '{"competitor":1}\n'); });
      assert.equal(result.attempt, 2);
      assert.deepEqual(JSON.parse(remoteFile(f, 'data/stats/other.json')), { competitor: 1 });
      assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.original);
    });
    test(`${profile}: repeated non-conflicting push races stop at three attempts and keep artifact`, () => {
      const f = fixture('limit-' + profile, profile); let attempts = 0;
      assert.throws(() => publish(f, ({ attempt }) => { attempts = attempt; advance(f, 'data/stats/other.json', JSON.stringify({ attempt })); }));
      assert.equal(attempts, 3); assert.ok(fs.existsSync(path.join(f.directory, 'manifest.json')));
      assert.deepEqual(JSON.parse(remoteFile(f, monitor)), { baseline: true });
    });
    test(`${profile}: changed destination stops on first conflict without losing generated payload`, () => {
      const f = fixture('conflict-' + profile, profile); let pushes = 0;
      assert.throws(() => publish(f, () => { pushes++; advance(f, profile === 'negative-clip' ? raw : monitor, '{"newer":true}\n'); }), /Source changed after capture/);
      assert.equal(pushes, 1); assert.ok(fs.existsSync(path.join(f.directory, 'manifest.json')));
      assert.deepEqual(JSON.parse(remoteFile(f, profile === 'negative-clip' ? raw : monitor)), { newer: true });
    });
    test(`${profile}: no-op artifact is valid but makes no commit`, () => {
      const f = fixture('noop-' + profile, profile, false);
      assert.equal(publish(f).status, 'no-changes'); assert.equal(git(f.remote, ['rev-parse', 'main']), f.expected.baseSha);
    });
  }
  test('raw source below limit follows unchanged reader/save contract', () => {
    const f = fixture('raw', 'negative-clip', true, false); publish(f);
    assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.next);
    assert.equal(git(f.remote, ['ls-tree', 'main', '--', gzip]), '');
  });
  test('already accepted push followed by a later writer is not duplicated', () => {
    const f = fixture('lost-ack');
    const result = publish(f, ({ attempt, savedSha }) => {
      if (attempt === 1) { git(f.work, ['push', 'origin', `${savedSha}:refs/heads/main`]); advance(f, 'data/stats/other.json', '{"afterAcceptance":true}\n'); }
    });
    assert.equal(result.status, 'already-persisted'); assert.equal(result.attempt, 1);
    assert.deepEqual(JSON.parse(zlib.gunzipSync(remoteFile(f, gzip))), f.next);
  });
  test('uncertain third push followed by a newer writer checks persistence without a fourth push', () => {
    const f = fixture('terminal-lost-ack'); let pushes = 0;
    const result = publish(f, ({ attempt, savedSha }) => {
      pushes++;
      if (attempt === 3) git(f.work, ['push', 'origin', `${savedSha}:refs/heads/main`]);
      advance(f, 'data/stats/other.json', JSON.stringify({ attempt }));
    });
    assert.equal(result.status, 'already-persisted'); assert.equal(result.attempt, 3); assert.equal(pushes, 3);
    assert.deepEqual(JSON.parse(zlib.gunzipSync(remoteFile(f, gzip))), f.next);
  });
  test('non-race rejection is not retried', () => {
    const f = fixture('reject'); let attempts = 0;
    write(f.remote, 'hooks/pre-receive', '#!/bin/sh\nexit 1\n'); fs.chmodSync(path.join(f.remote, 'hooks/pre-receive'), 0o755);
    assert.throws(() => publish(f, () => attempts++)); assert.equal(attempts, 1);
  });
  test('changed code is fail-closed before push', () => {
    const f = fixture('code'); advance(f, 'scripts/fixture.cjs', '// changed generator\n');
    assert.throws(() => publish(f), /Builder code changed/);
  });
  test('tampered run/attempt/source/profile/date or missing artifact ID cannot be published', () => {
    const f = fixture('identity');
    for (const [key, value] of [['runId', '102'], ['runAttempt', '2'], ['baseSha', '0'.repeat(40)], ['profile', 'active-100r'], ['date', '20261009'], ['artifactId', '']]) {
      const expected = { ...f.expected, [key]: value };
      assert.throws(() => checkpoint.load({ directory: f.directory, expected }));
    }
  });
  test('missing/tampered manifest or payload fails closed', () => {
    const f = fixture('missing');
    assert.throws(() => checkpoint.load({ directory: path.join(f.dir, 'absent'), expected: f.expected }));
    const manifest = JSON.parse(fs.readFileSync(path.join(f.directory, 'manifest.json')));
    const file = path.join(f.directory, 'files', manifest.files[0].sha256);
    const bytes = fs.readFileSync(file); fs.appendFileSync(file, 'tamper');
    assert.throws(() => publish(f), /Payload fingerprint/); fs.unlinkSync(file);
    assert.throws(() => publish(f)); fs.writeFileSync(file, bytes);
    fs.appendFileSync(path.join(f.directory, 'manifest.json'), ' ');
    assert.throws(() => publish(f), /Manifest hash/);
  });
  for (const [name, change] of [
    ['forbidden path', m => m.files[0].path = 'data/results/20261010.json'],
    ['path traversal', m => m.files[0].path = '../outside'],
    ['duplicate path', m => m.files.push(m.files[0])],
    ['incorrect guard', m => m.guards[0].baseBlob = '0'.repeat(40)],
    ['raw deletion', m => m.files = [{ path: raw, baseBlob: m.guards[0].baseBlob, operation: 'delete' }]],
  ]) test(name + ' rejected even with matching manifest hash', () => {
    const f = fixture('invalid-' + name.replaceAll(' ', '-')); mutateManifest(f, change);
    assert.throws(() => publish(f));
  });
  test('pack rejects unstaged/staged unexpected files and nonregular generated data', () => {
    const f = fixture('pack-invalid');
    write(f.work, 'data/results/20261010.json', '{"changed":true}\n');
    assert.throws(() => checkpoint.pack({ root: f.work, profile: 'negative-clip', date: '20261010', output: path.join(f.dir, 'other-bundle'), runId: '101', runAttempt: '1' }), /Unexpected generated file/);
  });
  test('paired archive removal publishes only with replacement raw and keeps original fields', () => {
    const f = fixture('archive-to-raw', 'negative-clip', false);
    prepare.preparePredictionGitSave({ rootDirectory: f.work, date: '20261010', rawSaveLimitBytes: 1 });
    commit(f.work); git(f.work, ['push', 'origin', 'main']);
    write(f.work, raw, JSON.stringify(f.next) + '\n');
    prepare.preparePredictionGitSave({ rootDirectory: f.work, date: '20261010', rawSaveLimitBytes: 100000 });
    fs.rmSync(f.directory, { recursive: true, force: true });
    const packed = checkpoint.pack({ root: f.work, profile: 'negative-clip', date: '20261010', output: f.directory, runId: '101', runAttempt: '1' });
    f.expected.baseSha = packed.baseSha; f.expected.manifestSha256 = packed.manifestSha256;
    publish(f);
    assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.next);
    assert.equal(git(f.remote, ['ls-tree', 'main', '--', gzip, meta]), '');
  });
  test('existing archive changes are guarded even when raw source is unchanged', () => {
    const f = fixture('archive-conflict');
    advance(f, meta, '{"newerArchive":true}\n');
    assert.throws(() => publish(f), /Source changed after capture/);
    assert.deepEqual(JSON.parse(remoteFile(f, raw)), f.original);
  });
  test('pack refuses incomplete archive pair', () => {
    const f = fixture('incomplete-pair', 'negative-clip', false);
    write(f.work, gzip, zlib.gzipSync('{}'));
    assert.throws(() => checkpoint.pack({ root: f.work, profile: 'negative-clip', date: '20261010', output: path.join(f.dir, 'bad'), runId: '101', runAttempt: '1' }), /Archive pair incomplete/);
  });
  test('symlink payload is rejected even if its target bytes match', () => {
    const f = fixture('symlink');
    const manifest = JSON.parse(fs.readFileSync(path.join(f.directory, 'manifest.json')));
    const payload = path.join(f.directory, 'files', manifest.files[0].sha256), target = path.join(f.dir, 'target');
    fs.copyFileSync(payload, target); fs.unlinkSync(payload); fs.symlinkSync(target, payload);
    assert.throws(() => publish(f), /nonregular payload/);
  });
  test('publisher-only rerun validates original capture attempt without rerunning capture', () => {
    const f = fixture('publisher-rerun');
    const helper = path.join(__dirname, '../scripts/generated-data-checkpoint.cjs');
    const env = { ...process.env, GITHUB_RUN_ID: '101', GITHUB_RUN_ATTEMPT: '2',
      CAPTURE_RUN_ID: '101', CAPTURE_RUN_ATTEMPT: '1', CHECKPOINT_DATE: '20261010',
      BASE_SHA: f.expected.baseSha, ARTIFACT_ID: '202', MANIFEST_SHA256: f.expected.manifestSha256,
      GITHUB_OUTPUT: '', GITHUB_STEP_SUMMARY: '' };
    assert.throws(() => execFileSync(process.execPath, [helper, 'publish', 'negative-clip', f.directory],
      { cwd: f.work, env: { ...env, CAPTURE_RUN_ID: '102' }, stdio: 'pipe' }));
    const result = JSON.parse(execFileSync(process.execPath, [helper, 'publish', 'negative-clip', f.directory], { cwd: f.work, env, encoding: 'utf8' }));
    assert.equal(result.status, 'saved');
    assert.deepEqual(JSON.parse(zlib.gunzipSync(remoteFile(f, gzip))), f.next);
  });
  test('workflow contract: compute outside lock, backup before publish, exact artifact ID/hash, bounded publish-only job', () => {
    for (const [file, job] of [['collect-frame-rise-fall-negative-clip-ab.yml', 'publish_comparison'], ['check-active-100r-early-monitor.yml', 'publish_monitor']]) {
      const source = fs.readFileSync(path.join(__dirname, '../.github/workflows', file), 'utf8');
      const [compute, writer] = source.split(`\n  ${job}:`);
      assert.ok(writer); assert.doesNotMatch(compute, /group: chappy-main-data-writers|contents: write/);
      assert.match(compute, /actions\/upload-artifact@v4/); assert.match(compute, /if-no-files-found: error/); assert.match(compute, /retention-days: 3\s/);
      assert.match(writer, /group: chappy-main-data-writers\n\s+queue: max\n\s+cancel-in-progress: false/);
      assert.match(writer, /artifact-ids: \$\{\{ needs\./); assert.match(writer, /MANIFEST_SHA256:/);
      assert.ok(writer.indexOf('Require uploaded checkpoint identity') < writer.indexOf('actions/download-artifact@v4'));
      assert.match(writer, /generated-data-checkpoint.cjs publish/);
      assert.doesNotMatch(writer, /build-|restore-daily|prepare-daily|git (push|pull|rebase)/);
      assert.match(writer, /if: github.event_name != 'pull_request'/);
    }
  });
  console.log(`generated checkpoint: ${checks} checks passed`);
} finally { fs.rmSync(root, { recursive: true, force: true }); }
