'use strict';
const assert = require('node:assert');
const mod = require('../scripts/inner-attack-holdout-final-ticket.cjs');
assert.strictEqual(mod.HOLDOUT_START, '20260819');
assert.deepStrictEqual(mod.CANDIDATE, { st:0.75, roleAttack:0.5, exhibition:0, maxCourseGap:null, penalty:4 });
const report = mod.build();
assert.strictEqual(report.scope.holdoutUsed, true);
assert.strictEqual(report.scope.productionChanged, false);
assert.strictEqual(report.scope.featureDefinition, 'PR-690/search-inner-attack-threshold-grid');
assert.ok(report.diagnostics.eligible >= 0);
assert.ok(report.diagnostics.replayable >= 0);
assert.ok(report.diagnostics.triggered >= 0);
assert.ok(report.diagnostics.rankingChangedOnTrigger >= 0);
assert.ok(report.result.races >= 0);
console.log(JSON.stringify(report, null, 2));
