'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const mod = require('../scripts/build-playful-link-position-forward.cjs');
const f = require('./helpers/report-input-fixture.cjs');
f.withArchive(root => {
  const records = Array.from({ length: 5 }, (_, i) => f.prediction(i + 1));
  records[1].prediction.practicalTickets = [];
  records[1].prediction.practicalSelection.tickets = ['1-2-3'];
  records[2].prediction.candidate24Tickets = [];
  records[3].selectedAt = records[3].deadlineAt;
  records[4].prediction.practicalTickets = ['1-2-3', '1-2-3', '1-3-4'];
  const results = records.map(r => f.official(r)); results[0].trifecta.combination = '1-4-3';
  f.saveDay(root, '20261003', records, [f.prediction(2), f.prediction(4)], results);
  const discovery = f.prediction(1, '20260923'); f.saveDay(root, '20260923', [discovery]);
  const r = f.parity(mod, root);
  assert.equal(r.productionChanged, false); assert.equal(r.automaticApplication, false);
  assert.equal(r.preregistration.discoveryDateExcluded, true);
  assert.equal(r.rows.length, 2); assert.equal(r.diagnostics.beforeRegistration, 1);
  assert.equal(r.diagnostics.missingBase, 1); assert.equal(r.diagnostics.noAddedLinkCandidate, 1);
  assert.deepEqual(r.rows[0].base, ['1-2-3']);
  assert.deepEqual(r.rows[0].added, ['1-4-3', '1-3-2', '1-5-2']);
  assert.deepEqual(r.rows[0].candidate, ['1-2-3', '1-4-3', '1-3-2', '1-5-2']);
  assert.equal(r.baseline.stakeYen, 300); assert.equal(r.candidate.stakeYen, 900);
  assert.equal(r.baseline.hits, 1); assert.equal(r.candidate.hits, 2); assert.equal(r.delta.newHits, 1);
  assert.equal(r.delta.profitYen, 600);
});
f.withArchive(root => {
  const registeredAt = require('../data/experiments/playful-link-position-v1.json').registeredAt;
  const start = Date.parse(registeredAt);
  const records = [-1, 0, 1, 2].map((offset, index) => {
    const record = f.prediction(index + 1, '20260924');
    record.selectedAt = new Date(start + offset).toISOString();
    record.deadlineAt = new Date(start + 3600000).toISOString();
    record.prediction.preRaceConditions.sourceFetchedAt = record.selectedAt;
    return record;
  });
  const results = records.map(record => f.official(record));
  results[3].trifecta.payout = 0;
  f.saveDay(root, '20260924', records, [], results);
  const report = f.parity(mod, root);
  assert.equal(report.diagnostics.beforeRegistration, 2, 'registration instant itself is excluded');
  assert.deepEqual(report.rows.map(row => row.raceKey), [records[2].raceKey], 'only strictly later rows with a payout are evaluated');
});
const workflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/collect-playful-link-position-forward.yml'), 'utf8');
assert.match(workflow, /workflow_run\.conclusion == 'cancelled'/);
console.log('playful link forward: deterministic parity, registration, ordering, candidate accounting passed');
