'use strict';
const assert=require('node:assert');
const {buildTheoryValidationReport,classifyReasons}=require('../scripts/theory-validation-report.cjs');
let r=buildTheoryValidationReport({theoryId:'x',diagnostics:{eligible:100,replayable:90,triggered:8,excludedMissingFrozenFeatures:10,reasons:{'frozen-ai-core-replay-unavailable':10,triggered:8}},result:{races:100,propagation:{rankingChanged:3,ticketsChanged:0},hits:{baseline:10,candidate:10,added:0,lost:0,net:0},tickets:{baseline:50,candidate:50,delta:0},roi:{baseline:80,candidate:80,delta:0}}});
assert.strictEqual(r.status,'PROPAGATION_BLOCKED');
assert.strictEqual(r.completion.complete,true);
assert.strictEqual(r.completion.validated,true);
assert.strictEqual(r.coverage.replayAccountingComplete,true);
assert.strictEqual(r.failureClassification.replayBlocked,10);
assert(r.warnings.some(x=>x.code==='THEORY_TRIGGERED_WITHOUT_TICKET_CHANGE'));
assert(r.warnings.some(x=>x.code==='FROZEN_INPUT_MISSING'));
r=buildTheoryValidationReport({theoryId:'y',diagnostics:{eligible:20,replayable:20,triggered:0},result:{races:20}});
assert.strictEqual(r.status,'NO_TRIGGER');
assert.strictEqual(r.completion.decisionReady,true);
assert.strictEqual(r.productionChanged,false);
r=buildTheoryValidationReport({theoryId:'z',diagnostics:{eligible:20,replayable:19,triggered:0},result:{races:18}});
assert.strictEqual(r.completion.complete,false);
assert(r.warnings.some(x=>x.code==='REPLAY_ACCOUNTING_MISMATCH'));
assert(r.warnings.some(x=>x.code==='RESULT_COHORT_MISMATCH'));
assert.deepStrictEqual(classifyReasons({'baseline-top-not-1':4,'candidate-condition-not-met':5,triggered:1}),{triggered:1,notTriggered:9,replayBlocked:0,other:0});
console.log('theory validation report tests passed');
