'use strict';
const assert=require('node:assert');
const {build}=require('../scripts/theory-validation-phase7-lifecycle.cjs');
const out=build();
assert.strictEqual(out.productionChanged,false);
assert.strictEqual(out.phaseComplete,true);
assert.strictEqual(out.summary.theories,13);
assert.strictEqual(new Set(out.rows.map(r=>r.theoryId)).size,13);
assert.strictEqual(out.audit.uniqueTheoryRegistry,true);
assert.strictEqual(out.audit.missingOrGenericState,0);
assert.strictEqual(out.audit.duplicateCollectors,0);
assert.strictEqual(out.audit.rejectedCandidateReexecution,0);
assert.strictEqual(out.audit.prospectiveHandoffBroken,0);
assert.strictEqual(out.audit.productionChanged,false);
assert.strictEqual(out.audit.historicalContradictions,0);
assert.strictEqual(out.audit.wallCollectorIncludesPhase6Handoff,true);
assert.strictEqual(out.audit.wallCollectorIncludesPhase7Lifecycle,true);
const wall=out.rows.find(r=>r.theoryId==='wall');
assert.ok(wall);
assert.strictEqual(wall.candidate.present,true);
assert.strictEqual(wall.prospectiveGate.required,100);
assert.ok(wall.prospectiveGate.current>=0);
assert.ok(['PENDING_GATE','REJECTED','CANDIDATE_FOR_USER_APPROVAL'].includes(wall.decisionStatus));
const newEnv=out.rows.find(r=>r.theoryId==='newEnvironment');
assert.strictEqual(newEnv.decisionStatus,'PERMANENT_BLOCKER');
assert.strictEqual(newEnv.blockerCode,'NO_FIXED_CANDIDATE_FROM_DISCOVERY');
for(const row of out.rows){
  assert.strictEqual(row.productionAdoptionStatus,'CURRENT_PRODUCTION_UNCHANGED');
  assert.ok(row.nextAllowedAction);
  if(row.decisionStatus==='REJECTED') assert.ok(row.nextAllowedAction.startsWith('NONE_'));
  if(row.decisionStatus==='PERMANENT_BLOCKER') assert.strictEqual(row.candidate.present,false);
}
console.log('theory validation phase7 lifecycle tests passed');
