'use strict';
const assert=require('node:assert');
const {build}=require('../scripts/theory-validation-phase6-prospective-integration.cjs');
const wallReport=require('../data/stats/wall-established-attacker2-skip-ab-report.json');
const r=build();
assert.strictEqual(r.productionChanged,false);
assert.strictEqual(r.phaseComplete,true);
assert.strictEqual(r.summary.duplicateCollection,0);
assert.strictEqual(r.summary.missing,0);
const wall=r.rows.find(x=>x.theoryId==='wall');
assert(wall);
const current=Number(wallReport?.diagnostics?.targetSettledRaceCount||0);
const required=Number(wallReport?.interpretation?.minimumFormalDecisionRaceCount||100);
const checkpoint=(wallReport?.checkpoints||[]).find(x=>Number(x?.targetSettledRaceCount)===required)||null;
const reached=current>=required && checkpoint?.reached===true;
const candidateConditionsMet=reached && checkpoint?.conditionsMet===true;
assert.strictEqual(wall.status,reached?'DECISION_READY':'PROSPECTIVE_GATE');
assert.strictEqual(wall.progress.current,current);
assert.strictEqual(wall.progress.required,required);
assert.strictEqual(wall.progress.remaining,Math.max(0,required-current));
assert.strictEqual(wall.collection.existingRoute,true);
assert.strictEqual(wall.collection.duplicateCollection,false);
assert.strictEqual(wall.evaluation.automaticAtGate,true);
assert.strictEqual(wall.evaluation.baseline.hits,Number(wallReport?.a?.hitCount||0));
assert.strictEqual(wall.evaluation.hits.net,-Number(wallReport?.delta?.missedHitCount||0));
assert.strictEqual(wall.evaluation.profitDelta,Number(wallReport?.delta?.profit||0));
assert.strictEqual(wall.evaluation.decision,reached?(candidateConditionsMet?'CANDIDATE_FOR_USER_APPROVAL':'REJECTED_BY_PREREGISTERED_GATE'):'WAITING_FOR_100R');
assert.strictEqual(wall.evaluation.userApprovalRequired,true);
const ne=r.rows.find(x=>x.theoryId==='newEnvironment');
assert(ne);
assert.strictEqual(ne.status,'PERMANENT_BLOCKER');
assert.strictEqual(ne.blockerCode,'NO_FIXED_CANDIDATE_FROM_DISCOVERY');
assert.strictEqual(ne.evidence.formalRaces,0);
assert.strictEqual(ne.collection.duplicateCollection,false);
assert.strictEqual(ne.evaluation.automaticAt100,false);
assert.strictEqual(ne.evaluation.discoveryCandidateFrozen,false);
console.log('phase6 prospective integration tests passed');
