'use strict';
const assert=require('node:assert');
const {build,BLOCKED_TARGETS}=require('../scripts/theory-validation-phase5-decisionability.cjs');
const r=build();
assert.strictEqual(r.productionChanged,false);
assert.strictEqual(r.phaseComplete,true);
assert.strictEqual(r.summary.blockedFromPhase4,10);
assert.strictEqual(r.rows.length,10);
assert.strictEqual(new Set(r.rows.map(x=>x.theoryId)).size,10);
assert.deepStrictEqual([...r.rows.map(x=>x.theoryId)].sort(),[...BLOCKED_TARGETS].sort());
assert.strictEqual(r.summary.decisionReady,1);
assert.strictEqual(r.summary.prospectiveGate,2);
assert.strictEqual(r.summary.permanentBlocker,7);
assert.strictEqual(r.summary.missing,0);
assert.strictEqual(r.summary.invalidClass,0);
assert.strictEqual(r.summary.genericBlocker,0);
assert.strictEqual(r.summary.duplicateCollection,0);
const course=r.rows.find(x=>x.theoryId==='course');
assert.strictEqual(course.phase5Class,'DECISION_READY');
assert.strictEqual(course.validated,true);
assert.strictEqual(course.decisionReady,true);
assert.strictEqual(course.conclusion,'REJECT_CANDIDATE');
assert.strictEqual(course.context.settledComparableCount,100);
assert.strictEqual(course.metrics.hitNet,-28);
const wall=r.rows.find(x=>x.theoryId==='wall');
assert.strictEqual(wall.phase5Class,'PROSPECTIVE_GATE');
assert.strictEqual(wall.gate.current,31);
assert.strictEqual(wall.gate.required,100);
assert.strictEqual(wall.gate.duplicateCollectionAdded,false);
const ne=r.rows.find(x=>x.theoryId==='newEnvironment');
assert.strictEqual(ne.phase5Class,'PROSPECTIVE_GATE');
assert.strictEqual(ne.gate.current,0);
assert.strictEqual(ne.gate.required,100);
assert.strictEqual(ne.gate.duplicateCollectionAdded,false);
for(const id of ['stSlit','exhibition','local','waterWeather','racerSkill','motorMaintenance','raceTrend']){
 const row=r.rows.find(x=>x.theoryId===id);
 assert.strictEqual(row.phase5Class,'PERMANENT_BLOCKER');
 assert.ok(row.blockerCode);
 assert.ok(row.reason);
 assert.strictEqual(row.metrics.measurementState,'NOT_MEASURED');
}
console.log('theory validation phase5 decisionability tests passed');
