'use strict';
const assert=require('node:assert');
const {build}=require('../scripts/theory-validation-phase6-prospective-integration.cjs');
const r=build();
assert.strictEqual(r.productionChanged,false);
assert.strictEqual(r.phaseComplete,true);
assert.strictEqual(r.summary.duplicateCollection,0);
assert.strictEqual(r.summary.missing,0);
const wall=r.rows.find(x=>x.theoryId==='wall');
assert(wall);
assert.strictEqual(wall.status,'PROSPECTIVE_GATE');
assert.strictEqual(wall.progress.current,31);
assert.strictEqual(wall.progress.required,100);
assert.strictEqual(wall.progress.remaining,69);
assert.strictEqual(wall.collection.existingRoute,true);
assert.strictEqual(wall.collection.duplicateCollection,false);
assert.strictEqual(wall.evaluation.automaticAtGate,true);
assert.strictEqual(wall.evaluation.baseline.hits,7);
assert.strictEqual(wall.evaluation.hits.net,-7);
assert.strictEqual(wall.evaluation.profitDelta,17230);
assert.strictEqual(wall.evaluation.decision,'WAITING_FOR_100R');
assert.strictEqual(wall.evaluation.userApprovalRequired,true);
const ne=r.rows.find(x=>x.theoryId==='newEnvironment');
assert(ne);
assert.strictEqual(ne.status,'PERMANENT_BLOCKER');
assert.strictEqual(ne.blockerCode,'NO_FIXED_CANDIDATE_FROM_DISCOVERY');
assert.strictEqual(ne.evidence.formalRaces,0);
assert.strictEqual(ne.collection.duplicateCollection,false);
assert.strictEqual(ne.evaluation.automaticAt100,false);
assert.strictEqual(ne.evaluation.discoveryCandidateFrozen,false);
console.log('phase6 prospective integration tests passed');
