'use strict';
const assert=require('node:assert');
const {build,TARGETS}=require('../scripts/theory-validation-phase4-terminal-audit.cjs');
const r=build();
assert.strictEqual(TARGETS.length,12);
assert.strictEqual(r.phaseComplete,true);
assert.strictEqual(r.productionChanged,false);
assert.strictEqual(r.summary.theories,12);
assert.strictEqual(r.summary.missing,0);
assert.strictEqual(r.summary.nonTerminal,0);
assert.strictEqual(r.summary.genericBlocker,0);
assert.strictEqual(r.summary.rejected,2);
assert.strictEqual(r.summary.blocked,10);
const by=Object.fromEntries(r.rows.map(x=>[x.theoryId,x]));
assert.strictEqual(by.holdPickup.blockerCode,'REJECTED_HOLDOUT_ROI_WORSE');
assert.strictEqual(by.holdPickup.metrics.triggered,56);
assert.strictEqual(by.holdPickup.metrics.hitNet,0);
assert.strictEqual(by.holdPickup.metrics.roiDeltaPt,-2);
assert.strictEqual(by.wall.blockerCode,'PROSPECTIVE_GATE_NOT_REACHED');
assert.strictEqual(by.wall.metrics.triggered,31);
assert.strictEqual(by.wall.context.minimumDecisionRaceCount,100);
assert.strictEqual(by.local.blockerCode,'COMBINED_LOCAL_WATER_EFFECT_NOT_SEPARABLE');
assert.strictEqual(by.waterWeather.blockerCode,'COMBINED_LOCAL_WATER_EFFECT_NOT_SEPARABLE');
assert.strictEqual(by.stSlit.blockerCode,'NO_STANDALONE_CANDIDATE');
assert.strictEqual(by.exhibition.blockerCode,'NO_STANDALONE_CANDIDATE');
assert.strictEqual(by.course.blockerCode,'NO_INDEPENDENT_HOLDOUT');
assert.strictEqual(by.flow.blockerCode,'REJECTED_STANDALONE_FLOW_SIGNAL');
assert.strictEqual(by.newEnvironment.blockerCode,'NO_DECISION_READY_NEW_ENGINE_COHORT');
for(const row of r.rows){assert.strictEqual(row.builderAvailable,true,`${row.theoryId}: builder unavailable`);assert.notStrictEqual(row.blockerCode,'NO_CANDIDATE_MUTATOR');}
console.log('phase4 terminal theory audit tests passed');
